server:
  port: 8083
  servlet:
    context-path: /api/submit
spring:
  application:
    name: pyoj-backend-submit-service
  profiles: # default dev env
    active: dev
  mvc: # for swagger3
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_oj
    username: root
    password: root
mybatis-plus:
  type-handlers-package: com.baomidou.mybatisplus.extension.handlers
knife4j:
  enable: true
