server:
  port: 8080
spring:
  application:
    name: pyoj-backend-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: pyoj-backend-user-service
          uri: lb://pyoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: pyoj-backend-question-service
          uri: lb://pyoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: pyoj-backend-submit-service
          uri: lb://pyoj-backend-submit-service
          predicates:
            - Path=/api/submit/**
  profiles: # default dev env
    active: dev
  mvc: # for swagger3
    pathmatch:
      matching-strategy: ant_path_matcher
#knife4j:
#  gateway:
#    enabled: true
#    strategy: discover
#    discover:
#      enabled: true
#      version: swagger2
knife4j:
  gateway:
    enabled: true
    strategy: manual  #手动模式
    routes:
      - name: PYOJ Backend User Service
        service-name: pyoj-backend-user-service
        url: /api/user/v3/api-docs
        context-path: /api/user
      - name: PYOJ Backend Question Service
        service-name: pyoj-backend-question-service
        url: /api/question/v3/api-docs
        context-path: /api/question
      - name: PYOJ Backend Submit Service
        service-name: pyoj-backend-submit-service
        url: /api/submit/v3/api-docs
        context-path: /api/submit
