server:
  port: 8084
  servlet:
    context-path: /api/judge

spring:
  application:
    name: pyoj-backend-judge-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  autoconfigure:
     exclude: # drop database drive
       - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  # default dev env
  profiles:
    active: dev

  # for swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


codesandbox:
  type: py # fake or py


