server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: pyoj-backend
  profiles:
    active: dev # default dev env
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # for swagger3
  session:
    store-type: redis
    timeout: 720000s
    redis:
      namespace: spring:session
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_oj
    username: root
    password: root
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
mybatis-plus:
  type-handlers-package: com.baomidou.mybatisplus.extension.handlers
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
knife4j:
  enable: true
codesandbox:
  type: py # fake or py
