server:
  port: 8082
  servlet:
    context-path: /api/question
spring:
  application:
    name: pyoj-backend-question-service
  profiles: # default dev env
    active: dev
  mvc: # for swagger3
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_oj
    username: root
    password: root
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
mybatis-plus:
  type-handlers-package: com.baomidou.mybatisplus.extension.handlers
knife4j:
  enable: true
